# -*- coding: utf-8 -*-

line = '+++++++++++++++++++++++++++++++++'
game = ('doom', 'diablo', 23, ['compaq', 'ibm', 'hp', 'dell', 'apple'])
for abc in game:
    print(abc)
print(line)

sum0 = 0
for x in [1,2,3,4,5]:
    sum0 = sum0 + x
print(sum0)
print(list(range(20)))  # a list of 0-19 generated by range()

# way 1
sum1 = 0
for y in range(101):
    sum1 = sum1 + y
print('sum1=', sum1)

# way 2
sum2 = 0
n = 100
while n > 0:
    sum2 = sum2 + n
    n = n - 1
print('sum2=', sum2)

# way 3
sum3 = 0
m = 0
while m < 101:
    sum3 = sum3 + m
    m = m + 1
print('sum3=', sum3)

print(line, 'break', line)

sum4 = 0
m = 0
while m < 301:
    sum4 = sum4 + m
    if m == 100:
        print('break', m)
        break
    m = m + 1
print('sum4=', sum4)
print(line)

sum5 = 0
m = 0
for m in list(range(6)):
    if m % 2 != 0:  # 如果m是奇数.
        continue  # 跳过本次循环
    sum5 = sum5 + m
print(sum5)
print(line)

for p in list(range(11)):
    if p % 2 == 0:
        continue
    print(p)  # 仅打印奇数
